#!/bin/bash
cd hge
#############################################################################
cd CxImage
echo Compiling CxImage...
g++ -c *.cpp -D_LINUX
ar rcs libCxImage.a *.o
rm *.o
cd ..
mv ./CxImage/libCxImage.a libCxImage.a
#############################################################################
cd ZLIB
echo Compiling zlib...
gcc -c *.c
ar rcs libz.a *.o
rm *.o
cd ..
mv ./ZLIB/libz.a libz.a
#############################################################################
echo Compiling libhge...
g++ -c *.cpp -I/usr/include/SDL/ -I../include
ar rcs libhge.a *.o
rm *.o
cd ..
mv ./hge/*.a ./
#############################################################################
cd hgehelp
echo Compiling libhgehelp...
g++ -c *.cpp -I../include
ar rcs libhgehelp.a *.o
rm *.o
cd ..
mv ./hgehelp/libhgehelp.a libhgehelp.a
#############################################################################
echo Compiling the main executable...
g++ *.cpp -I/usr/include/freetype2 -I./include \
-lSDL -lvorbis -lvorbisfile -lopenal -ljpeg -lpng -lfreetype \
-Wl,libhgehelp.a,libhge.a,libCxImage.a,libz.a -o BulletLabRemixII
#############################################################################
rm *.a
strip BulletLabRemixII
cd ..